/**
 * Light-hearted "IT Majdoor" quotes shown on the landing page.
 * A big pile of relatable, funny developer/corporate one-liners.
 */
export const QUOTES: string[] = [
  // The daily corporate grind
  "Born to live, forced to say: 'Let's connect offline on this.'",
  "My life is split into two phases: waiting for the weekend, and dreading Monday morning.",
  "We are all just highly educated laborers digging digital ditches for offshore clients.",
  "A 'quick sync' is never quick, and it is never just a sync.",
  "Estimate: 2 days. Reality: 2 days plus the heat death of the universe.",
  "The meeting could have been an email. The email could have been a Slack. The Slack could have been silence.",
  "I don't have a work-life balance. I have a work-work balance with occasional sleep.",
  "'Circling back' is corporate for 'I forgot about this until just now.'",
  "My calendar is 80% meetings about the work I don't have time to do.",
  "Every 'ASAP' is urgent until you actually deliver it ASAP.",
  "The coffee machine is the true single point of failure in this company.",
  "'Let's take this offline' means the conversation will never happen again.",
  "I'm not slacking, I'm waiting for the build to finish.",
  "Working from home: where the standup is the only proof you're alive.",
  "Friday deploys are just adrenaline sports for developers.",

  // Coding & technical reality
  "My code works, and I have absolutely no idea why. Do not touch it.",
  "Fixing one bug usually means opening a subscription for three new ones.",
  "The project deadline is tomorrow, but the requirement document is still a work in progress.",
  "Nothing is more permanent than a temporary fix in production.",
  "99 little bugs in the code, take one down, patch it around, 127 little bugs in the code.",
  "It's not a bug, it's an undocumented feature.",
  "There are two hard things in computer science: cache invalidation, naming things, and off-by-one errors.",
  "My code doesn't have bugs, it just develops random unexpected features.",
  "I spent 6 hours debugging, and it was a missing semicolon.",
  "Copy-pasting from Stack Overflow is a legitimate architectural decision.",
  "The definition of insanity is running the same test and expecting it to pass this time.",
  "Real programmers count from 0.",
  "Weeks of coding can save you hours of planning.",
  "First, solve the problem. Then, write the code. Then, wonder what past-me was thinking.",
  "A good programmer looks both ways before crossing a one-way street.",
  "Documentation is like a love letter you write to your future self.",
  "I turned it off and on again, and now I'm a senior engineer.",
  "The best error message is the one that never shows up.",
  "Deleted code is debugged code.",
  "It compiles! Ship it.",
  "My favorite language is coffee, it compiles into code.",
  "Git commit -m 'stuff'. Future me will figure it out.",
  "There's no place like 127.0.0.1.",
  "Programming is 10% writing code and 90% figuring out why it doesn't work.",
  "The code was working yesterday. I have witnesses.",
  "I don't always test my code, but when I do, I do it in production.",
  "Legacy code is just code that works and nobody understands.",
  "Refactoring: making the code slightly less terrible than before.",
  "The rubber duck understands my code better than my teammates.",
  "Software and cathedrals are much the same: first we build them, then we pray.",
  "Regex: now you have two problems.",
  "To understand recursion, you must first understand recursion.",
  "It's not dead code, it's resting.",

  // Appraisals & management
  "Management wants Google-level innovation on a local kirana store budget.",
  "My manager asked for a status update. The status is: I am actively updating my resume.",
  "The reward for doing good work is always more work.",
  "Our company's 'flexible working hours' just means you can work any 14 hours of the day.",
  "Appraisal season: where 'exceeds expectations' translates to a 2% raise.",
  "We're a family here — the kind that expects you to work weekends unpaid.",
  "'We value your feedback' — then proceeds to change nothing.",
  "The performance review measures how good I am at attending meetings.",
  "'Wearing many hats' is HR for 'we won't hire enough people.'",
  "Promotion criteria: do three people's jobs, get one person's title.",
  "Unlimited PTO means you'll feel too guilty to ever take it.",
  "The bonus is always just around the corner, and the corner keeps moving.",
  "My raise didn't beat inflation, but the pizza party was catered.",
  "'We're like a startup' — the equity is imaginary and so are the boundaries.",
  "Every reorg is just musical chairs with worse music.",

  // Client communications
  "As per my last email... which you clearly deleted without reading.",
  "The client doesn't know what they want, but they know for sure that what I built isn't it.",
  "Aligning expectations usually means lowering my standard of living for the next sprint.",
  "'Make it pop' is not a requirement, it's a cry for help.",
  "The client wants it fast, cheap, and good. They can pick zero of the three.",
  "'Small change' is the four most terrifying words in software.",
  "Scope creep is just the client's way of saying 'I love your work, do more for free.'",
  "'It should be simple' is how every three-month project begins.",
  "The requirements are frozen — until the client thaws them again tomorrow.",
  "'Can you also just add...' — no. The answer is no.",
  "Client feedback: 'I'll know it when I see it.' Great, so will I. Eventually.",
  "The final version is never final. There is only final_v2_FINAL_actualfinal.",
  "They approved the mockup, then acted surprised the product looked like it.",
  "'Quick call?' is client for 'I'm about to change everything.'",
  "The demo works perfectly until the client is watching.",

  // Standup confessions
  "In today's standup I'll say 'no blockers' and then quietly cry into my coffee.",
  "It works on my machine — so clearly the problem is all your machines.",
  "'I'll refactor it later' is the most beautiful lie in software.",
  "My standup update: same as yesterday, but with more despair.",
  "'Almost done' has been my status for three sprints straight.",
  "I said 'no updates' because 'I broke prod' felt too honest.",
  "Yesterday: meetings. Today: meetings. Blockers: the meetings.",
  "I estimated it at one story point out of pure optimism.",
  "'Working as intended' is what I say when I can't reproduce it.",
  "Standup is just group therapy where nobody gets better.",

  // Existential dev humor
  "I became a developer to avoid talking to people. Now I'm in six calls a day.",
  "Impostor syndrome is just my code reviewing itself.",
  "I don't fear AI taking my job. I fear it inheriting my codebase.",
  "Every senior engineer is just a junior who learned to Google better.",
  "The cloud is just someone else's computer having a bad day.",
  "I have 100 browser tabs open and 0 answers.",
  "My most productive hours are the ones right before the deadline.",
  "Sleep is just a feature I keep deprioritizing in my backlog.",
  "Ctrl+Z is the closest thing I have to a time machine.",
  "I'm not procrastinating, I'm letting my subconscious architect the solution.",
  "The only thing scaling faster than our users is our tech debt.",
  "My rubber duck just filed for emotional distress.",
  "I write code so future me can suffer in new and exciting ways.",
  "Coffee: because adulting and debugging require caffeine.",
  "Somewhere, my code is running. I choose not to think about where.",
];
